version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run.sh
    ports:
      - "${API:-8000}:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password_default}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_default}
      POSTGRES_PORT: ${DB_PORT:-5432}
