# Generated by Django 2.1.7 on 2019-03-19 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitute', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('delivered', models.BooleanField(default=False)),
                ('postman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postwoman.PostWoman')),
            ],
        ),
    ]
