# Generated by Django 2.1.7 on 2019-03-20 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0002_auto_20190319_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
