# Generated by Django 2.1.7 on 2019-03-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0003_postoffice'),
    ]

    operations = [
       migrations.AddField(
            model_name='postwoman',
            name='postoffice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postwoman.PostOffice'),
            preserve_default=False,
        ),
    ]
