# Generated by Django 2.1.7 on 2019-03-20 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0004_auto_20190320_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('postwoman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postwoman.PostWoman')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
