# Generated by Django 2.1.7 on 2019-03-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0005_placetovisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetovisit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postwoman',
            name='postoffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postwoman.PostOffice'),
        ),
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together={('latitude', 'longitude', 'date', 'postwoman')},
        ),
        migrations.AlterUniqueTogether(
            name='placetovisit',
            unique_together={('name', 'postwoman')},
        ),
    ]
