# Generated by Django 2.1.7 on 2019-03-21 20:51

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0006_auto_20190320_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('route', django.contrib.postgres.fields.jsonb.JSONField()),
                ('postwoman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postwoman.PostWoman')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('date', 'postwoman')},
        ),
    ]
