# Generated by Django 2.1.7 on 2019-03-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postwoman', '0007_auto_20190321_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
